// Code generated by go-swagger; DO NOT EDIT.

// Package restapi LRU Cache
//
//	LRU Cache API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /lru-cache/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
