// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CacheResponse cache response
//
// swagger:model CacheResponse
type CacheResponse struct {

	// The retrieved value (for GET)
	Value string `json:"value,omitempty"`
}

// Validate validates this cache response
func (m *CacheResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cache response based on context it is used
func (m *CacheResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CacheResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CacheResponse) UnmarshalBinary(b []byte) error {
	var res CacheResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
