// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CacheItem cache item
//
// swagger:model CacheItem
type CacheItem struct {

	// The key to store
	Key string `json:"key,omitempty"`

	// The value to store
	Value string `json:"value,omitempty"`
}

// Validate validates this cache item
func (m *CacheItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cache item based on context it is used
func (m *CacheItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CacheItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CacheItem) UnmarshalBinary(b []byte) error {
	var res CacheItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
