// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"lru-cache/models"
)

// LrucacheGetOKCode is the HTTP code returned for type LrucacheGetOK
const LrucacheGetOKCode int = 200

/*
LrucacheGetOK Successful retrieval

swagger:response lrucacheGetOK
*/
type LrucacheGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.CacheResponse `json:"body,omitempty"`
}

// NewLrucacheGetOK creates LrucacheGetOK with default headers values
func NewLrucacheGetOK() *LrucacheGetOK {

	return &LrucacheGetOK{}
}

// WithPayload adds the payload to the lrucache get o k response
func (o *LrucacheGetOK) WithPayload(payload *models.CacheResponse) *LrucacheGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the lrucache get o k response
func (o *LrucacheGetOK) SetPayload(payload *models.CacheResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LrucacheGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LrucacheGetNotFoundCode is the HTTP code returned for type LrucacheGetNotFound
const LrucacheGetNotFoundCode int = 404

/*
LrucacheGetNotFound Key not found in cache

swagger:response lrucacheGetNotFound
*/
type LrucacheGetNotFound struct {
}

// NewLrucacheGetNotFound creates LrucacheGetNotFound with default headers values
func NewLrucacheGetNotFound() *LrucacheGetNotFound {

	return &LrucacheGetNotFound{}
}

// WriteResponse to the client
func (o *LrucacheGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
