// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LrucachePostHandlerFunc turns a function with the right signature into a lrucache post handler
type LrucachePostHandlerFunc func(LrucachePostParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LrucachePostHandlerFunc) Handle(params LrucachePostParams) middleware.Responder {
	return fn(params)
}

// LrucachePostHandler interface for that can handle valid lrucache post params
type LrucachePostHandler interface {
	Handle(LrucachePostParams) middleware.Responder
}

// NewLrucachePost creates a new http.Handler for the lrucache post operation
func NewLrucachePost(ctx *middleware.Context, handler LrucachePostHandler) *LrucachePost {
	return &LrucachePost{Context: ctx, Handler: handler}
}

/*
	LrucachePost swagger:route POST /set lrucachePost

# Set a key-value pair in the cache

Stores a key-value pair in the cache.
*/
type LrucachePost struct {
	Context *middleware.Context
	Handler LrucachePostHandler
}

func (o *LrucachePost) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLrucachePostParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
