// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LrucachePostCreatedCode is the HTTP code returned for type LrucachePostCreated
const LrucachePostCreatedCode int = 201

/*
LrucachePostCreated Key-value pair successfully stored

swagger:response lrucachePostCreated
*/
type LrucachePostCreated struct {
}

// NewLrucachePostCreated creates LrucachePostCreated with default headers values
func NewLrucachePostCreated() *LrucachePostCreated {

	return &LrucachePostCreated{}
}

// WriteResponse to the client
func (o *LrucachePostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
